apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ws
  labels:
    app: demo-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ws
  template:
    metadata:
      labels:
        app: demo-ws
    spec:
      containers:
      - name: demo-ws
        imagePullPolicy: Always
        image: registry.cn-shanghai.aliyuncs.com/kubesre01/demo-ws
        ports:
        - containerPort: 8090
--- 
apiVersion: v1
kind: Service
metadata:
  name: demo-ws-svc
spec:
  type: ClusterIP
  selector:
    app: demo-ws
  ports:
    - port: 8090
      targetPort: 8090