apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-intent-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voice-intent-service
  template:
    metadata:
      labels:
        app: voice-intent-service
    spec:
      containers:
      - name: voice-intent
        image: your-registry/voice-intent-service:1.0.0  # 替换为你的镜像地址
        ports:
        - containerPort: 8080
        env:
        - name: ASR_ENDPOINT  # 可从 ConfigMap/Secret 读取
          value: "wss://dashscope.aliyuncs.com/api-ws/v1/inference"
        - name: LLM_ENDPOINT
          value: "https://dashscope.aliyuncs.com/api/v1/services/llm"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: voice-intent-service
  namespace: default
spec:
  selector:
    app: voice-intent-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080